In [1]:
# Python_Practice_解多元线性回归方程_GF_2023-09-23.ipynb

# Create By GF 2023-09-23 19:50

import numpy as np

In [2]:
# 现实中披萨价格的影响因素应该不止直径一个,这里引入了辅料的因素:

# 训练集数据：

# +---------+-----------+---------+-----------+
# |训练样本 |直径(英寸) |辅料种类 |价格(美元) |
# +---------+-----------+---------+-----------+
# |1        |8          |11       |9.7759     |
# |2        |9          |8.5      |10.7522    |
# |3        |11         |15       |12.7048    |
# |4        |16         |18       |17.5863    |
# |5        |12         |11       |13.6811    |
# +---------+-----------+---------+-----------+

# 对于以上训练集数据:
#
# X(i) = (X(i)1, X(i)2)
# X(1) = (8, 11)
# X(2) = (9, 8.5)
# ...
#
# 对于系数Theta(以下用K代替):
#
# Matrix_K = (K0, K1, K2, ...)
#
# Y = K0 + K1·X1 + K2·X2 + ... Kn·Xn
#
# 由于X和K的结构不整齐, 所以虚构第0个特征X0, 另其恒等于1:
#
# X(i) = (1, X(i)1, X(i)2)
# X(1) = (1, 8, 11)
# X(2) = (1, 9, 8.5)
# ...
#
# Matrix_X = {(1, 8, 11),
#             (1, 9, 8.5),
#             ...}
#
# 预测Y值:
# Predict_Y = Matrix_X · Matrix_K
# Predict_Y = {(1, 8, 11),    {K0,
#              (1, 9, 8.5), ·  K1,
#              ...}            K2,
#                              ...}

# 测试集数据：

# +---------+-----------+---------+-----------+
# |训练样本 |直径(英寸) |辅料种类 |价格(美元) |
# +---------+-----------+---------+-----------+
# |1        |8          |2        |11         |
# |2        |9          |0        |8.5        |
# |3        |11         |2        |15         |
# |4        |16         |2        |18         |
# |5        |12         |0        |11         |
# +---------+-----------+---------+-----------+

In [3]:
Matrix_X = np.array([[1, 8, 11],
                     [1, 9, 8.5],
                     [1, 11, 15],
                     [1, 16, 18],
                     [1, 12, 11]])
Matrix_X

array([[ 1. ,  8. , 11. ],
       [ 1. ,  9. ,  8.5],
       [ 1. , 11. , 15. ],
       [ 1. , 16. , 18. ],
       [ 1. , 12. , 11. ]])

In [4]:
# shape[0]表示最外围的数组的维数, shape[1]表示次外围的数组的维数, 数字不断增大, 维数由外到内.
print("Matrix_X 最外维的长度为 %d" % Matrix_X.shape[0])

Matrix_X 最外维的长度为 5


In [5]:
Matrix_Y = np.array([9.7759,
                     10.7522,
                     12.7048,
                     17.5863,
                     13.6811])
Matrix_Y

array([ 9.7759, 10.7522, 12.7048, 17.5863, 13.6811])

In [6]:
# shape[0]表示最外围的数组的维数, shape[1]表示次外围的数组的维数, 数字不断增大, 维数由外到内.
print("Matrix_Y 最外维的长度为 %d" % Matrix_Y.shape[0])

Matrix_Y 最外维的长度为 5


In [7]:
Matrix_X.T

array([[ 1. ,  1. ,  1. ,  1. ,  1. ],
       [ 8. ,  9. , 11. , 16. , 12. ],
       [11. ,  8.5, 15. , 18. , 11. ]])

In [8]:
Matrix_X.dot(Matrix_X.T)

array([[186.  , 166.5 , 254.  , 327.  , 218.  ],
       [166.5 , 154.25, 227.5 , 298.  , 202.5 ],
       [254.  , 227.5 , 347.  , 447.  , 298.  ],
       [327.  , 298.  , 447.  , 581.  , 391.  ],
       [218.  , 202.5 , 298.  , 391.  , 266.  ]])

In [9]:
Matrix_X.T.dot(Matrix_X)

array([[  5.  ,  56.  ,  63.5 ],
       [ 56.  , 666.  , 749.5 ],
       [ 63.5 , 749.5 , 863.25]])

In [10]:
# Matrix_K = (Matrix_X_T · Matrix_X)的逆 · Matrix_X_T · Matrix_Y

In [11]:
# numpy.linalg 模块包含线性代数的函数.
# 使用这个模块, 可以计算逆矩阵, 求特征值, 解线性方程组以及求解行列式等.
# inv函数计算逆矩阵.

Matrix_K = np.linalg.inv(Matrix_X.T.dot(Matrix_X)).dot(Matrix_X.T).dot(Matrix_Y)
Matrix_K

array([1.96550000e+00, 9.76300000e-01, 6.16633875e-16])

In [12]:
# Other:

In [13]:
X_b = np.hstack([np.ones((len(Matrix_X), 1)), Matrix_X])

In [14]:
np.ones((len(Matrix_X)))

array([1., 1., 1., 1., 1.])

In [15]:
np.hstack([np.ones((len(Matrix_X), 1)), Matrix_X])

array([[ 1. ,  1. ,  8. , 11. ],
       [ 1. ,  1. ,  9. ,  8.5],
       [ 1. ,  1. , 11. , 15. ],
       [ 1. ,  1. , 16. , 18. ],
       [ 1. ,  1. , 12. , 11. ]])